_wandb:
    value:
        cli_version: 0.19.10
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 2
                - 14
                - 16
                - 23
                - 55
                - 67
                - 69
            "4": 3.11.11
            "5": 0.19.10
            "8":
                - 5
            "12": 0.19.10
            "13": linux-x86_64
batch_size:
    value: 128
epochs:
    value: 15
sharding_strategy:
    value: 1
world_size:
    value: 8
