_wandb:
    value:
        cli_version: 0.19.10
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 1
                - 2
                - 3
                - 13
                - 16
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.10
            "8":
                - 5
            "12": 0.19.10
            "13": linux-x86_64
batch_size:
    value: 128
epochs:
    value: 10
lr:
    value: 0.001
model:
    value: vgg16
sharding_strategy:
    value: FULL_SHARD
